image: node:latest

stages:
  - pre
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
variables:
  DOCKER_DRIVER: overlay2


before_script:
  - echo "WKWK"
  - export CLICKUP=$CLICKUP
  - echo $CLICKUP
  - echo $GITLAB_PRIVATE_TOKEN
  - yarn install

create:merge-request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: pre
  before_script: []
  except:
    - production
    - master
    - tags
  script:
    - gitlab_auto_mr -t master -c WIP -d .gitlab/merge_request_templates/merge_request.md --private-token $GITLAB_PRIVATE_TOKEN -r -s --use-issue-name

lint:
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^master/
  script:
    - yarn lint
tests:unit:
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^master/
  script:
    - yarn test --silent
